sudo: required
services:
  - docker

before_install:
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t philmui/client-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true philmui/client-react-test npm test

after_success:
  - docker build -t philmui/multi-client ./client
  - docker build -t philmui/multi-nginx ./nginx
  - docker build -t philmui/multi-server ./server
  - docker build -t philmui/multi-worker ./worker

  # take these images & push to docker hub
  - docker push philmui/multi-client
  - docker push philmui/multi-nginx
  - docker push philmui/multi-server
  - docker push philmui/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: 'elasticbeanstalk-us-east-2-044537394587'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY